name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Vercel Environment Variables
      run: |
        echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> $GITHUB_ENV
        echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_STAGING_PROJECT_ID }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Create .env file
      run: |
        echo "JWT_SECRET=\"${{ secrets.STAGING_JWT_SECRET }}\"" >> .env
        echo "DATABASE_URL=\"${{ secrets.STAGING_DATABASE_URL }}\"" >> .env
        echo "FIREBASE_WEB_API_KEY=\"${{ secrets.FIREBASE_WEB_API_KEY }}\"" >> .env
        echo "FIREBASE_PROJECT_ID=\"${{ secrets.FIREBASE_PROJECT_ID }}\"" >> .env
        echo "FIREBASE_CLIENT_EMAIL=\"${{ secrets.FIREBASE_CLIENT_EMAIL }}\"" >> .env
        echo "FIREBASE_PRIVATE_KEY=\"${{ secrets.FIREBASE_PRIVATE_KEY }}\"" >> .env
        echo "ACCESS_CODE_EXPIRY=\"1y\"" >> .env
        echo "ENV=\"staging\"" >> .env

    - name: Build project
      run: npm run build

    - name: Install Vercel CLI
      run: npm i -g vercel@latest

    - name: Deploy to Vercel
      run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod