name: Deploy to Vercel

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Vercel Environment Variables
      run: |
        echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> $GITHUB_ENV
        echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_DEV_PROJECT_ID }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Create .env file
      run: |
        echo "JWT_SECRET=${{ secrets.DEV_JWT_SECRET }}" >> .env
        echo "DATABASE_URL=${{ secrets.DEV_DATABASE_URL }}" >> .env
        echo "ACCESS_CODE_EXPIRY=1y" >> .env
        echo "ENV=development" >> .env

    - name: Build project
      run: npm run build

    - name: Install Vercel CLI
      run: npm i -g vercel@latest

    - name: Deploy to Vercel
      run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod